version = 0.1

[default.deploy.parameters]
stack_name = "carcharge-app"
resolve_s3 = true
s3_prefix = "carcharge-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
